apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  name: deployment-demo-ar
spec:
  args:
  - name: service-name
    value: deployment-demo.argo-demo.svc.cluster.local
  metrics:
  - name: test
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: test
                image: ryanpedersen42/deployment-demo:canary
                command: [chmod u+x hello-world.sh && ./hello-world.sh, deployment-demo.argo-demo.svc.cluster.local]
              restartPolicy: Never
  # metrics:
  # - name: webmetric
  #   successCondition: 'true' == 'true'
  # metrics:
  # - name: success-rate
  #   interval: 5m
  #   successCondition: 'true' == 'true'
  #   failureLimit: 3
  #   provider:
  #     prometheus:
  #       address: http://prometheus-k8s.monitoring.svc.cluster.local:9090
  #       query: |
  #         sum(response_status{app="{{args.service-name}}",role="canary",status=~"2.*"})/sum(response_status{app="{{args.service-name}}",role="canary"})
  # # - name: error-rate
  # #   interval: 5m
  # #   successCondition: result[0] <= 0.95
  # #   failureLimit: 3
  # #   provider:
  # #     prometheus:
  # #       address: http://prometheus-k8s.monitoring.svc:9090
  # #       query: |
  # #         sum(irate(
  # #           istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code=~"5.*"}[5m]
  # #         )) /
  # #         sum(irate(
  # #           istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[5m]
  # #         ))