apiVersion: argoproj.io/v1alpha1
kind: AnalysisRun
metadata:
  name: deployment-demo-ar
spec:
  args:
  - name: service-name
    value: deployment-demo.default.svc.cluster.local
  metrics:
  - name: success-rate
    interval: 5m
    successCondition: result[0] >= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc:9090
        query: |
          :node_memory_MemAvailable_bytes:sum
  - name: error-rate
    interval: 5m
    successCondition: result[0] <= 0.95
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc:9090
        query: |
          :node_memory_MemAvailable_bytes:sum